---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - neofetch
        - htop
        - lf
        - tree
        - clang
        - cmake
        - git
        - docker
        - valgrind
        - tmux
        - neovim
        - firefox
        - obsidian
        - arduino-ide

  - name: copy hyprland files
    copy:
      src:  files/hyprland
      dest: $HOME/.config/hypr
      owner:  $USER
      group:  $USER

  - name: add ansible-pull cron job
    cron:
      name: "ansible-pull"
      minute: "*/10"
      user: root
      job: "/usr/bin/ansible-pull -U https://github.com/moha-bekh/Ansible_Desktop.git"
