---
- hosts: localhost
  connection: local
  become: true
  vars:
    HOME: "/home/moha"
    USER: "moha"
  tasks:
    - name: install packages
      package:
        name:
          - neofetch
          - htop
          - lf
          - tree
          - cron
          - clang
          - cmake
          - git
          - docker
          - valgrind
          - tmux
          - neovim
          - firefox
          - obsidian
          - arduino-ide
          - nautilus
          - wofi
          - waybar
          - hyprpaper
          - hypridle
          - blueman
          - pavucontrol

    - name: add ansible-pull cron job
      cron:
        name: "ansible-pull"
        minute: "*/10"
        user: root
        job: "/usr/bin/ansible-pull -o -U https://github.com/moha-bekh/Ansible_Desktop.git"

    - name: copy hyprland configurations files
      copy:
        src: files/hyprland.conf/
        dest: "{{ HOME }}/.config/hypr"
        owner: "{{ USER }}"
        group: "{{ USER }}"

    - name: copy hyprland additional packages
      copy:
        src: files/hyprland.pkg/
        dest: "{{ HOME }}/.config/"
        owner: "{{ USER }}"
        group: "{{ USER }}"

    - name: copy fonts
      copy:
        src: files/fonts/
        dest: /usr/share/fonts
        owner: root
        group: root

    - name: Create tmp dir for yay installation
      file:
        path: "/tmp/yay-install"
        state:  directory
        mode: '0755'

    - name: Clone yay repo
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay-install
        clone:  yes
        depth:  1

    - name: Build and install yay
      command:  makepkg -si --noconfirm
      args:
        chdir:  /tmp/yay-install
        creates:  /usr/bin/yay

    - name: Installer les packages AUR individuellement si nécessaire
      shell: |
        if ! command -v hyprshot &> /dev/null; then
          echo "installing hyprshot..."
          yay -S --noconfirm hyprshot
        fi
        
        if ! command -v hyprlock &> /dev/null; then
          echo "installing hyprlock..."
          yay -S --noconfirm hyprlock
        fi
        
        if ! command -v swaync &> /dev/null; then
          echo "installing swaync..."
          yay -S --noconfirm swaync
        fi
      register: install_result
      changed_when: "'installing of' in install_result.stdout"
