---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - neofetch
        - htop
        - net-tools
        - iproute2
        - lf
        - tree
        - clang
        - cmake
        - git
        - docker
        - kubectl
        - kubeadm
        - kubelet
        - valgrind
        - tmux
        - neovim
        - firefox
        - obsidian
        - arduino-ide
