---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - neofetch
        - htop
        - lf
        - tree
        - cron
        - clang
        - cmake
        - git
        - docker
        - valgrind
        - tmux
        - neovim
        - firefox
        - obsidian
        - arduino-ide
        - nautilus
        - wofi
        - waybar
        - hyprpaper
        - hyprlock
        - swaync
        - hypridle
        - blueman
        - pavucontrol

  - name: copy hyprland files
    copy:
      src:  files/hyprland
      dest: /home/moha/.config/hypr
      owner:  moha
      group:  moha

  - name: add ansible-pull cron job
    cron:
      name: "ansible-pull"
      minute: "*/10"
      user: root
      job: "/usr/bin/ansible-pull -o -U https://github.com/moha-bekh/Ansible_Desktop.git"
