---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - neofetch
        - htop
        - lf
        - tree
        - clang
        - cmake
        - git
        - docker
        - valgrind
        - tmux
        - neovim
        - firefox
        - obsidian
        - arduino-ide

  - name: copy hyprland files
    copy:
      src:  files/hyprland
      dest: $HOME/.config/hypr
      owner:  $USER
      group:  $USER

  - name: set up sudo for ansible user
    copy:
      src:  files/sudoer_x
      dest: /etc/sudoers.d/sudoer_x
      owner:  root
      group:  root
      mode: 0440
  - name: add ansible-pull cron job
    user: sudoer_x
    minute: "*/10"
    job: ansible-pull -o U https://github.com/moha-bekh/Ansible_Desktop.git
