---
- hosts: localhost
  connection: local
  become: true
  vars:
    HOME: "/home/moha"
    USER: "moha"
  tasks:
    - name: install pacman packages
      package:
        name:
          - neofetch
          - htop
          - lf
          - tree
          - cron
          - clang
          - cmake
          - git
          - docker
          - valgrind
          - tmux
          - neovim
          - firefox
          - obsidian
          - arduino-ide
          - nautilus
          - wofi
          - waybar
          - hyprpaper
          - hypridle
          - blueman
          - pavucontrol

    - name: add ansible-pull cron job
      cron:
        name: "ansible-pull"
        minute: "*/10"
        user: root
        job: "/usr/bin/ansible-pull -o -U https://github.com/moha-bekh/Ansible_Desktop.git"

    - name: copy bashrc
      copy:
        src: files/bashrc/
        dest: "{{ HOME }}/"
        owner: "{{ USER }}"
        group: "{{ USER }}"

    - name: copy hyprland configurations files
      copy:
        src: files/hyprland.conf/
        dest: "{{ HOME }}/.config/hypr"
        owner: "{{ USER }}"
        group: "{{ USER }}"

    - name: copy hyprland additional packages
      copy:
        src: files/hyprland.pkg/
        dest: "{{ HOME }}/.config/"
        owner: "{{ USER }}"
        group: "{{ USER }}"

    - name: copy fonts
      copy:
        src: files/fonts/
        dest: /usr/share/fonts
        owner: root
        group: root

    - name: Create tmp dir for yay installation
      file:
        path: "/tmp/yay-install"
        state:  directory
        mode: '0755'

    - name: Clone yay repo
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: /tmp/yay-install
        clone:  yes
        depth:  1

    - name: Build and install yay
      become: yes
      become_user:  "{{ USER }}"
      command:  makepkg -si --noconfirm
      args:
        chdir:  /tmp/yay-install
        creates:  /usr/bin/yay

    - name: install hyprlock
      ansible.builtin.command: yay -S --noconfirm hyprlock
      args:
        creates: /usr/bin/hyprlock

    - name: install hyprlock
      ansible.builtin.command: yay -S --noconfirm hyprlock
      args:
        creates: /usr/bin/hyprlock

    - name: install hyprshot
      ansible.builtin.command: yay -S --noconfirm hyprshot
      args:
        creates: /usr/bin/hyprshot

    - name: install swaync
      ansible.builtin.command: yay -S --noconfirm swaync
      args:
        creates: /usr/bin/swaync

    - name: Install yay packages
      shell: |
          echo "installing Cascadia code nerd..."
          yay -Sy --noconfirm ttf-cascadia-code-nerd
          echo "installing nwg-look..."
          yay -Sy --noconfirm nwg-look
          echo "installing catppuccin-gtk-theme-mocha..."
          yay -Sy --noconfirm catppuccin-gtk-theme-mocha
      register: install_result
      changed_when: "'installing of' in install_result.stdout"
