---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install htop
    - package:
        name: htop

  tasks:
    - name: install neofetch
    - package:
        name: neofetch
